# Dockerfile for CentOS
# Currently used as "unsupported" linux test version

FROM quay.io/centos/centos:stream9
# CentOS has moved to a rolling release mode
# Stream 9 supported until 2027

ENV PATH=/opt/gnat/bin:/opt/gprbuild/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    # Refresh rolling repositories
RUN dnf makecache && \
    # BASE TOOLS. --allowerasing needed for curl to replace curl-minimal
    dnf install -y --allowerasing \
        bzip2 \
        curl \
        epel-release \
        fontconfig \
        gcc \
        git \
        jq \
        libX11 \
        libX11-xcb \
        make \
        redhat-rpm-config \
        subversion \
        sudo \
        unzip \
        wget

# The base install uses curl-minimal, which causes a conflict the moment one of
# our crates tries to install the regular curl. So, have it installed already
# here.

# For some reason these are not found during the first install run ??
RUN dnf install -y mercurial

# PYTHON PIP v3 (for e3)
RUN dnf install -y \
        python3-devel \
        python3

# GNAT FSF via alr
RUN wget https://github.com/alire-project/alire/releases/download/v2.0.2/alr-2.0.2-bin-x86_64-linux.zip \
        -O /tmp/alr.zip && \
    unzip /tmp/alr.zip -d /tmp && \
    cp /tmp/bin/alr /usr/bin/alr && \
    chmod +x /usr/bin/alr && \
    alr -C /opt get gnat_native && \
    alr -C /opt get gprbuild && \
    rm /usr/bin/alr && \
    mv /opt/gnat* /opt/gnat && \
    mv /opt/gprbuild* /opt/gprbuild

RUN cat /etc/os-release && \
    gnat --version && \
    gprbuild --version
