# Dockerfile for Debian stable GNAT

FROM debian:stable

RUN apt-get update && \
    apt-get install -y \
        bash \
        curl \
        git \
        gnat \
        gprbuild \
        mercurial \
        python-pip \
        subversion \
        sudo \
        unzip \
        wget && \
    apt-get clean && \
\
    pip install e3-testsuite
