# Dockerfile for CentOS
# Currently used as "unsupported" linux test version

FROM quay.io/centos/centos:stream9
# CentOS has moved to a rolling release mode
# Stream 9 supported until 2027

ENV PATH=/opt/gnat/bin:/opt/gprbuild/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    # Refresh rolling repositories
RUN dnf makecache && \
    # BASE TOOLS
    dnf install -y \
        bzip2 \
        epel-release \
        fontconfig \
        gcc \
        git \
        libX11 \
        libX11-xcb \
        make \
        redhat-rpm-config \
        subversion \
        sudo \
        unzip \
        wget

#        curl \         # Already included in base install

# For some reason these are not found during the first install run ??
RUN dnf install -y mercurial

# PYTHON PIP v3 (for e3)
RUN dnf install -y \
        python3-devel \
        python3

# GNAT FSF via alr
RUN wget https://github.com/alire-project/alire/releases/download/v1.2.2/alr-1.2.2-bin-x86_64-linux.zip \
        -O /tmp/alr.zip && \
    unzip /tmp/alr.zip -d /tmp && \
    cp /tmp/bin/alr /usr/bin/alr && \
    chmod +x /usr/bin/alr && \
    alr toolchain --install gnat_native gprbuild --install-dir /opt && \
    rm /usr/bin/alr && \
    mv /opt/gnat* /opt/gnat && \
    mv /opt/gprbuild* /opt/gprbuild && \
    gnat --version && \
    gprbuild --version
