# Dockerfile for Ubuntu LTS GNAT

# latest is actually latest LTS
FROM ubuntu:latest  

RUN ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime && \
    apt-get update && \
    apt-get install -y \
        bash \
        curl \
        git \
        gnat \
        gprbuild \
        libpython3-dev \
        make \
        mercurial \
        python3-dev \
        python3-pip \
        subversion \
        sudo \
        tzdata \
        unzip \
        wget && \
    apt-get clean
