# Dockerfile for Debian stable GNAT

FROM debian:stable

RUN apt-get update && \
    apt-get install -y \
        bash \
        curl \
        git \
        gnat \
        gprbuild \
        libpython3-dev \
        mercurial \
        python3-dev \
        python3-pip \
        python3-venv \
        subversion \
        sudo \
        unzip \
        wget && \
    apt-get clean
