# Dockerfile for Debian stable GNAT

FROM debian:testing

RUN apt-get update && \
    apt-get install -y \
        bash \
        git \
        gnat \
        gprbuild \
        lsb-release \
        mercurial \
        subversion
