# Dockerfile for Debian stable GNAT

FROM debian:testing

RUN apt-get update && \
    apt-get install -y \
        bash \
        curl \
        git \
        gnat \
        gprbuild \
        mercurial \
        python3-pip \
        subversion \
        sudo \
        unzip \
        wget && \
    apt-get clean && \
\
    pip3 install e3-testsuite
